# Lokio Configuration File
# Author: Lokio
# Github: https://github.com/any-source/lokio
# Documentation: https://lokio.dev

name: angular-frontend
package: your-package

# Directory
dir:
  # client
  hook: src/hooks
  call: src/call
  component: src/interfaces/components
  screen: src/interfaces/screens
  layout: src/interfaces/layouts
