# Lokio Configuration File
# Author: Lokio
# Github: https://github.com/any-source/lokio
# Documentation: https://lokio.dev

name: elysia-backend
package: your-package

# Directory
dir:
  # client
  hook: src/hooks